version: '3.8'

services:
  db_app:
    image: postgres:latest
    container_name: ps03
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "database_app"
  db_auth:
    image: postgres:latest
    container_name: ps04
    ports:
      - "5433:5433"
    environment:
      PGPORT: "5433"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "database_auth"

  app:
    container_name: app01
    build: ./app
    ports:
      - '8000:8000'
    depends_on:
      - db_app
      - auth
    expose:
      - "8000"
    command: bash -c "sleep 5 && make migration && make run-project"
  auth:
    container_name: app02
    build: ./authentication
    ports:
      - '8800:8800'
    depends_on:
      - db_auth
    expose:
      - "8800"
    command: bash -c "sleep 5 && make migration && make run-project"
  nginx:
    image: nginx:alpine
    container_name: ng01
    depends_on:
      - app
      - auth
    volumes:
     - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - '80:80'